-- Migration: add extended certificate fields
ALTER TABLE certificates
  ADD COLUMN IF NOT EXISTS aadhar VARCHAR(50),
  ADD COLUMN IF NOT EXISTS dob VARCHAR(20),
  ADD COLUMN IF NOT EXISTS son_or_daughter_of VARCHAR(255),
  ADD COLUMN IF NOT EXISTS job_role VARCHAR(255),
  ADD COLUMN IF NOT EXISTS duration VARCHAR(100),
  ADD COLUMN IF NOT EXISTS training_center VARCHAR(255),
  ADD COLUMN IF NOT EXISTS district VARCHAR(255),
  ADD COLUMN IF NOT EXISTS state VARCHAR(255),
  ADD COLUMN IF NOT EXISTS assessment_partner VARCHAR(255),
  ADD COLUMN IF NOT EXISTS enrollment_no VARCHAR(100),
  ADD COLUMN IF NOT EXISTS issue_place VARCHAR(255);


